In [33]:
import numpy
import math

A = numpy.matrix([[0, 1, 1], [math.sqrt(2), 2, 0], [0, 1, 1]])
print(A)

[[0.         1.         1.        ]
 [1.41421356 2.         0.        ]
 [0.         1.         1.        ]]


In [34]:
At = numpy.transpose(A)
print(At)

[[0.         1.41421356 0.        ]
 [1.         2.         1.        ]
 [1.         0.         1.        ]]


In [35]:
AAt = numpy.dot(A, At)
print(AAt)

[[2. 2. 2.]
 [2. 6. 2.]
 [2. 2. 2.]]


In [36]:
from numpy import linalg
w, u = linalg.eig(AAt)
print(u)

[[-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [-8.16496581e-01  1.11954943e-16 -5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]


In [37]:
AtA=numpy.dot(At, A)
print(AtA)

[[2.         2.82842712 0.        ]
 [2.82842712 6.         2.        ]
 [0.         2.         2.        ]]


In [38]:
h, v = linalg.eig(AtA)
print(v)

[[-4.08248290e-01  7.07106781e-01 -5.77350269e-01]
 [-8.66025404e-01 -5.00000000e-01 -7.84321844e-17]
 [-2.88675135e-01  5.00000000e-01  8.16496581e-01]]


In [39]:
lengths = numpy.sqrt(numpy.sum(numpy.square(v), axis=1))
print(lengths)

[[1.]
 [1.]
 [1.]]


In [40]:
for i in range(numpy.size(v, 0)):
    for j in range(numpy.size(v, 1)):
        v[i, j] = v[i, j]/lengths[i]


Vt = numpy.transpose(v)
print(v)

[[-4.08248290e-01  7.07106781e-01 -5.77350269e-01]
 [-8.66025404e-01 -5.00000000e-01 -7.84321844e-17]
 [-2.88675135e-01  5.00000000e-01  8.16496581e-01]]


In [41]:
eigenv = numpy.asarray(w)
s = numpy.zeros(shape=(numpy.count_nonzero(eigenv),numpy.count_nonzero(eigenv)))
S = numpy.asarray(s)

for i in range(numpy.size(S, 0)):
    for j in range(numpy.size(S, 1)):
        if i==j:
            S[i][j] = numpy.sqrt(eigenv[i])        

print(S)

[[2.82842712e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.13503446e-08 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.41421356e+00]]


In [42]:
print("The answer is: ")
print("Matrix S:", S, "\n")
print("Matrix U:", u ,"\n")
print("Matrix V (transposed):", Vt)

The answer is: 
Matrix S: [[2.82842712e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.13503446e-08 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.41421356e+00]] 

Matrix U: [[-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [-8.16496581e-01  1.11954943e-16 -5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]] 

Matrix V (transposed): [[-4.08248290e-01 -8.66025404e-01 -2.88675135e-01]
 [ 7.07106781e-01 -5.00000000e-01  5.00000000e-01]
 [-5.77350269e-01 -7.84321844e-17  8.16496581e-01]]
